
version: "3"

services:
  database:
    image: "postgres:12"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_DB: "demoDB"
    ports:
      - "5430:5432"